name: Run dev job
on:
  workflow_dispatch:
concurrency:
  group: pages-dev
  cancel-in-progress: true
jobs:
  run:
    uses: ./.github/workflows/_run.yml
    with:
      branch: dev
      deploy_dir: dev
