name: Run dev job
on:
  workflow_dispatch:
  push:
    branches: ["dev"]
  schedule:
    - cron: "0 1,5,9,13,17,21 * * *"
    - cron: "0 19 * * *"
concurrency:
  group: pages-dev
  cancel-in-progress: true
jobs:
  run:
    uses: ./.github/workflows/_run.yml
    with:
      branch: dev
      deploy_dir: dev
      send_telegram: ${{ github.event_name == 'schedule' && github.event.schedule == '0 19 * * *' }}
    secrets:
      CLAUDE_CONFIG: ${{ secrets.CLAUDE_CONFIG }}
      TG_TOKEN: ${{ secrets.TG_TOKEN_DEV }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID_DEV }}
