name: Run prod job
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
#    - cron: "0 17 * * *"
    - cron: "0 13 * * *"
concurrency:
  group: pages-main
  cancel-in-progress: true
jobs:
  run:
    uses: ./.github/workflows/_run.yml
    with:
      branch: main
      send_telegram: ${{ github.event_name == 'schedule' && github.event.schedule == '0 13 * * *' }}
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      TG_TOKEN: ${{ secrets.TG_TOKEN_PROD }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID_PROD }}
