name: Run prod job
on:
  workflow_dispatch:
  push:
    branches: ["main"]
concurrency:
  group: pages-main
  cancel-in-progress: true
jobs:
  run:
    uses: ./.github/workflows/_run.yml
    with:
      branch: main
